/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import static dao.RefencesDAO.ShowRefencesTable;
import static dao.RefencesDAO.insertReferences;
import static dao.ScheduleReferencesDAO.checkngay;
import static dao.StudentDAO.compareStudent;
import static dao.StudentDAO.editStudent;
import static dao.TranscriptDAO.ShowScoresStudentTable;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import pojo.References;
import pojo.Students;

/**
 *
 * @author nguye
 */
public class MainStudent extends javax.swing.JFrame {

    private String username;

    /**
     * Creates new form MainStudent
     */
    public MainStudent() {
        initComponents();
        JStudentMain.removeAll();
        JStudentMain.repaint();
        JStudentMain.revalidate();
        // add panel
        JStudentMain.add(panelDiem);
        JStudentMain.repaint();
        JStudentMain.revalidate();
    }

    public MainStudent(String msv) {
        this.username = msv;
        initComponents();
        JStudentMain.removeAll();
        JStudentMain.repaint();
        JStudentMain.revalidate();
        // add panel
        JStudentMain.add(panelDiem);
        JStudentMain.repaint();
        JStudentMain.revalidate();
        ShowScoresStudentTable(tableStudent, msv);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btndsdiem = new javax.swing.JButton();
        btnphuckhao = new javax.swing.JButton();
        btnMatkhau = new javax.swing.JButton();
        JStudentMain = new javax.swing.JPanel();
        panelDiem = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableStudent = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtmmh = new javax.swing.JTextField();
        txtdiemgk = new javax.swing.JTextField();
        txtcuoiky = new javax.swing.JTextField();
        txtdiemkhac = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtlydo = new javax.swing.JTextArea();
        btntaopk = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txthten = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txttongdiem = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txttenmh = new javax.swing.JTextField();
        panelphuckhao = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablephuckhao = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        panelchangePass = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        matkhaucu = new javax.swing.JPasswordField();
        matkhaumoi = new javax.swing.JPasswordField();
        matkhaumoir = new javax.swing.JPasswordField();
        btnsubmit = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btndsdiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btndsdiem.setText("Danh sách điểm");
        btndsdiem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btndsdiem.setFocusable(false);
        btndsdiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndsdiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btndsdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndsdiemActionPerformed(evt);
            }
        });
        jToolBar1.add(btndsdiem);

        btnphuckhao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnphuckhao.setText("Phúc Khảo");
        btnphuckhao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnphuckhao.setFocusable(false);
        btnphuckhao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnphuckhao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnphuckhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphuckhaoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnphuckhao);

        btnMatkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMatkhau.setText("Đổi Mật khẩu");
        btnMatkhau.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMatkhau.setFocusable(false);
        btnMatkhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMatkhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatkhauActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMatkhau);

        JStudentMain.setLayout(new java.awt.CardLayout());

        tableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Số Sinh Viên", "Họ Và Tên", "Điểm Giữa Kỳ", "Điểm Cuối Kỳ", "Điểm Khác", "Điểm Tổng", "Môn Học", "Mã MH", "Kết Quả"
            }
        ));
        tableStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStudentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableStudent);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Danh Sách Điểm");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Thông Tin phúc Khảo"));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Mã Môn Học:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Điểm giữa Kỳ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Điểm cuối kỳ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Điểm Khác");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Lí Do");

        txtmmh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtdiemgk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtcuoiky.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtdiemkhac.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtlydo.setColumns(20);
        txtlydo.setRows(5);
        jScrollPane3.setViewportView(txtlydo);

        btntaopk.setText("Phúc Khảo");
        btntaopk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaopkActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Mã Môn Học:");

        txthten.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Môn Học");

        txttongdiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Tổng điểm");

        txttenmh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(btntaopk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthten, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttenmh, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmmh, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdiemgk, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(58, 58, 58)
                        .addComponent(txtcuoiky, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdiemkhac, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(txttongdiem))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(txtmmh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcuoiky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(txtdiemgk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdiemkhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txthten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txttongdiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txttenmh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btntaopk))
        );

        javax.swing.GroupLayout panelDiemLayout = new javax.swing.GroupLayout(panelDiem);
        panelDiem.setLayout(panelDiemLayout);
        panelDiemLayout.setHorizontalGroup(
            panelDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(panelDiemLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDiemLayout.setVerticalGroup(
            panelDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JStudentMain.add(panelDiem, "card3");

        tablephuckhao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ Số Sinh Viên", "Họ Và Tên", "Điểm Giữa Kỳ", "Điểm Cuối Kỳ", "Điểm Khác", "Điểm Tổng ", "Môn học", "Mã Môn Học", "lý do", "Trạng Thái"
            }
        ));
        jScrollPane4.setViewportView(tablephuckhao);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Thông Tin Phúc Khảo");

        javax.swing.GroupLayout panelphuckhaoLayout = new javax.swing.GroupLayout(panelphuckhao);
        panelphuckhao.setLayout(panelphuckhaoLayout);
        panelphuckhaoLayout.setHorizontalGroup(
            panelphuckhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
            .addComponent(jTextField1)
        );
        panelphuckhaoLayout.setVerticalGroup(
            panelphuckhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelphuckhaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        JStudentMain.add(panelphuckhao, "card4");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐỔI MẬT KHẨU");

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Mật Khẩu Cũ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Mật Khẩu Mới");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nhập Lại Mật Khẩu Mới");

        matkhaucu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        matkhaumoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        matkhaumoir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(matkhaucu, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addComponent(matkhaumoi)
                        .addComponent(matkhaumoir))
                    .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(matkhaucu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(matkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(matkhaumoir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnsubmit)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelchangePassLayout = new javax.swing.GroupLayout(panelchangePass);
        panelchangePass.setLayout(panelchangePassLayout);
        panelchangePassLayout.setHorizontalGroup(
            panelchangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelchangePassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelchangePassLayout.setVerticalGroup(
            panelchangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelchangePassLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 254, Short.MAX_VALUE))
        );

        JStudentMain.add(panelchangePass, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JStudentMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JStudentMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntaopkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaopkActionPerformed
        float diemgk = Float.parseFloat(txtdiemgk.getText());
        float diemck = Float.parseFloat(txtcuoiky.getText());
        float diemkhac = Float.parseFloat(txtdiemkhac.getText());
        float tongdiem = Float.parseFloat(txttongdiem.getText());
        String mamonh = txtmmh.getText();
        String lydo = txtlydo.getText();
        String hovaten = txthten.getText();
        String tenmhString = txttenmh.getText();
        Byte status = 0;
        References item = new References(this.username, hovaten, tenmhString,
                mamonh, diemgk, diemck, tongdiem, diemck, lydo, status);
        if (checkngay()) {
            if (insertReferences(item)) {
                JOptionPane.showMessageDialog(null, "Thêm thành công!!!");
                ShowScoresStudentTable(tableStudent, this.username);
                return;
            }
        }

        JOptionPane.showMessageDialog(null, "Thêm Thất Bại!!!");
    }//GEN-LAST:event_btntaopkActionPerformed

    private void btndsdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndsdiemActionPerformed
        JStudentMain.removeAll();
        JStudentMain.repaint();
        JStudentMain.revalidate();
        // add panel
        JStudentMain.add(panelDiem);
        JStudentMain.repaint();
        JStudentMain.revalidate();
    }//GEN-LAST:event_btndsdiemActionPerformed

    private void btnphuckhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphuckhaoActionPerformed
        ShowRefencesTable(tablephuckhao, this.username);
        JStudentMain.removeAll();
        JStudentMain.repaint();
        JStudentMain.revalidate();
        // add panel
        JStudentMain.add(panelphuckhao);
        JStudentMain.repaint();
        JStudentMain.revalidate();
    }//GEN-LAST:event_btnphuckhaoActionPerformed

    private void btnMatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatkhauActionPerformed
        JStudentMain.removeAll();
        JStudentMain.repaint();
        JStudentMain.revalidate();
        // add panel
        JStudentMain.add(panelchangePass);
        JStudentMain.repaint();
        JStudentMain.revalidate();
    }//GEN-LAST:event_btnMatkhauActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        String mkcu = matkhaucu.getText();
        String mkmoiString = matkhaumoi.getText();
        String mkmoi1 = matkhaumoir.getText();
        if (mkmoiString.trim().equals(mkmoi1)) {
            Students itemstudent = compareStudent(this.username, mkcu);
            itemstudent.setPassword(mkmoi1);
            if (itemstudent != null) {
                if (editStudent(itemstudent)) {
                    JOptionPane.showMessageDialog(null, "Thay đổi thành công!");
                    this.setVisible(false);
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            Login_Form form = new Login_Form();
                            //form.setExtendedState(JFrame.MAXIMIZED_BOTH);
                            form.setVisible(true);
                        }
                    });
                    return;
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Kiểm Tra Lại Mật Khẩu không đúng!!");
        return;
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void tableStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStudentMouseClicked
        JTable target = (JTable) evt.getSource();
        txthten.setText(tableStudent.getValueAt(target.getSelectedRow(), 1).toString());
        txtcuoiky.setText(tableStudent.getValueAt(target.getSelectedRow(), 2).toString());
        txtdiemkhac.setText(tableStudent.getValueAt(target.getSelectedRow(), 3).toString());
        txtdiemgk.setText(tableStudent.getValueAt(target.getSelectedRow(), 4).toString());
        txttongdiem.setText(tableStudent.getValueAt(target.getSelectedRow(), 5).toString());
        txttenmh.setText(tableStudent.getValueAt(target.getSelectedRow(), 6).toString());
        txtmmh.setText(tableStudent.getValueAt(target.getSelectedRow(), 7).toString());


    }//GEN-LAST:event_tableStudentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JStudentMain;
    private javax.swing.JButton btnMatkhau;
    private javax.swing.JButton btndsdiem;
    private javax.swing.JButton btnphuckhao;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton btntaopk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPasswordField matkhaucu;
    private javax.swing.JPasswordField matkhaumoi;
    private javax.swing.JPasswordField matkhaumoir;
    private javax.swing.JPanel panelDiem;
    private javax.swing.JPanel panelchangePass;
    private javax.swing.JPanel panelphuckhao;
    private javax.swing.JTable tableStudent;
    private javax.swing.JTable tablephuckhao;
    private javax.swing.JTextField txtcuoiky;
    private javax.swing.JTextField txtdiemgk;
    private javax.swing.JTextField txtdiemkhac;
    private javax.swing.JTextField txthten;
    private javax.swing.JTextArea txtlydo;
    private javax.swing.JTextField txtmmh;
    private javax.swing.JTextField txttenmh;
    private javax.swing.JTextField txttongdiem;
    // End of variables declaration//GEN-END:variables
}
