/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import static dao.ClassRoomDAO.GetcodeClass;
import static dao.ClassRoomDAO.showClassComboBoxModel;
import static dao.ScheduleDAO.ShowScheduleTable;
import static dao.StudentDAO.GetCodeStudent;
import static dao.StudentDAO.ShowStudentTable;
import static dao.StudentDAO.deleteStudent;
import static dao.StudentDAO.editStudent;
import static dao.StudentDAO.insertStudent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import pojo.Classroom;
import pojo.Students;

/**
 *
 * @author nguye
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        // check nam
        rnam.setSelected(true);
        //remove all
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        //add panel
        jPanelMain.add(panelStudent);
        jPanelMain.repaint();
        jPanelMain.revalidate();
        String lopAc = CbListClass.getSelectedItem().toString();
        ShowStudentTable(TableStudent, lopAc);
        showClassComboBoxModel(CbLop);
        showClassComboBoxModel(CbListClass);
        showClassComboBoxModel(CbLopLich);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        toolbarListStudent = new javax.swing.JButton();
        toolbarSchedule = new javax.swing.JButton();
        toolbarScores = new javax.swing.JButton();
        toolbarPhucKhao = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();
        panelListScore = new javax.swing.JPanel();
        panelThoikb = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CbLopLich = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableLich = new javax.swing.JTable();
        panelStudent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtmssv = new javax.swing.JTextField();
        txtcmnd = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        rnam = new javax.swing.JRadioButton();
        rnu = new javax.swing.JRadioButton();
        CbLop = new javax.swing.JComboBox<>();
        them = new java.awt.Button();
        sua = new java.awt.Button();
        button3 = new java.awt.Button();
        btndelete = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableStudent = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CbListClass = new javax.swing.JComboBox<>();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        toolbarListStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toolbarListStudent.setText("Danh Sách Sinh Viên");
        toolbarListStudent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toolbarListStudent.setFocusable(false);
        toolbarListStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolbarListStudent.setMargin(new java.awt.Insets(2, 14, 2, 15));
        toolbarListStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarListStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarListStudentActionPerformed(evt);
            }
        });
        jToolBar1.add(toolbarListStudent);

        toolbarSchedule.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toolbarSchedule.setText("Thời Khóa Biểu");
        toolbarSchedule.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toolbarSchedule.setFocusable(false);
        toolbarSchedule.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolbarSchedule.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarScheduleActionPerformed(evt);
            }
        });
        jToolBar1.add(toolbarSchedule);

        toolbarScores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toolbarScores.setText("Danh sách điểm");
        toolbarScores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toolbarScores.setFocusable(false);
        toolbarScores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolbarScores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarScoresActionPerformed(evt);
            }
        });
        jToolBar1.add(toolbarScores);

        toolbarPhucKhao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toolbarPhucKhao.setText("Danh sách phúc khảo");
        toolbarPhucKhao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toolbarPhucKhao.setFocusable(false);
        toolbarPhucKhao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolbarPhucKhao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarPhucKhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarPhucKhaoActionPerformed(evt);
            }
        });
        jToolBar1.add(toolbarPhucKhao);

        jPanelMain.setBackground(new java.awt.Color(102, 255, 102));
        jPanelMain.setLayout(new java.awt.CardLayout());

        panelListScore.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelListScoreLayout = new javax.swing.GroupLayout(panelListScore);
        panelListScore.setLayout(panelListScoreLayout);
        panelListScoreLayout.setHorizontalGroup(
            panelListScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        panelListScoreLayout.setVerticalGroup(
            panelListScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        jPanelMain.add(panelListScore, "card4");

        panelThoikb.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Quản lý thời khóa biểu");

        jLabel10.setText("Chọn Lớp:");

        CbLopLich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        CbLopLich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbLopLichActionPerformed(evt);
            }
        });

        TableLich.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Môn", "Tên Môn", "Phòng Học", "Lớp"
            }
        ));
        jScrollPane2.setViewportView(TableLich);

        javax.swing.GroupLayout panelThoikbLayout = new javax.swing.GroupLayout(panelThoikb);
        panelThoikb.setLayout(panelThoikbLayout);
        panelThoikbLayout.setHorizontalGroup(
            panelThoikbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelThoikbLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(26, 26, 26)
                .addComponent(CbLopLich, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        panelThoikbLayout.setVerticalGroup(
            panelThoikbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThoikbLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThoikbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CbLopLich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
        );

        jPanelMain.add(panelThoikb, "card3");

        panelStudent.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Sinh Viên");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Thêm Xóa Sửa Sinh Viên")));
        jPanel2.setName("Thêm Sửa Sinh Vien"); // NOI18N

        jLabel2.setText("Mã Số Sinh Viên:");

        jLabel3.setText("Họ Và Tên:");

        jLabel7.setText("Giới Tính:");

        jLabel8.setText("Chứng Minh Nhân Dân:");

        jLabel9.setText("Lớp:");

        buttonGroup1.add(rnam);
        rnam.setText("nam");

        buttonGroup1.add(rnu);
        rnu.setText("nu");

        CbLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbLopActionPerformed(evt);
            }
        });

        them.setActionCommand("btnthem");
        them.setLabel("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        sua.setActionCommand("btnSua");
        sua.setLabel("Sửa");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        button3.setActionCommand("btxReset");
        button3.setLabel("Làm Mới");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        btndelete.setActionCommand("btnXoa");
        btndelete.setLabel("Xóa");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmssv)
                            .addComponent(CbLop, 0, 136, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rnam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rnu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcmnd))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(sua, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(txtmssv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rnam)
                    .addComponent(rnu))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CbLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Số Sinh Viên", "Tên Sinh Viên", "Giới Tính", "Lớp", "Chứng minh nhân dân"
            }
        ));
        TableStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableStudent);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Danh Sách Sinh Viên");

        jLabel5.setText("Chọn Lớp: ");

        CbListClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        CbListClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbListClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelStudentLayout = new javax.swing.GroupLayout(panelStudent);
        panelStudent.setLayout(panelStudentLayout);
        panelStudentLayout.setHorizontalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CbListClass, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelStudentLayout.setVerticalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CbListClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelMain.add(panelStudent, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toolbarPhucKhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarPhucKhaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toolbarPhucKhaoActionPerformed

    private void toolbarListStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarListStudentActionPerformed
        String lopAc = CbListClass.getSelectedItem().toString();
        ShowStudentTable(TableStudent, lopAc);
//remove all
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        //add panel
        jPanelMain.add(panelStudent);
        jPanelMain.repaint();
        jPanelMain.revalidate();

        // add Table;

    }//GEN-LAST:event_toolbarListStudentActionPerformed

    private void toolbarScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarScoresActionPerformed

//remove all
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        //add panel
        jPanelMain.add(panelListScore);
        jPanelMain.repaint();
        jPanelMain.revalidate();
    }//GEN-LAST:event_toolbarScoresActionPerformed

    private void toolbarScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarScheduleActionPerformed
        String lopAc = CbLopLich.getSelectedItem().toString();
        ShowScheduleTable(TableLich, lopAc);
//remove all
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        //add panel
        jPanelMain.add(panelThoikb);
        jPanelMain.repaint();
        jPanelMain.revalidate();
    }//GEN-LAST:event_toolbarScheduleActionPerformed

    private void CbLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbLopActionPerformed

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        String lopAc = CbListClass.getSelectedItem().toString();
        String name = txtname.getText();
        String code = txtmssv.getText();
        String cmndString = txtcmnd.getText();
        Byte sex = 0;
        if (rnu.isSelected()) {
            sex = 1;
        }
        String lop = CbLop.getSelectedItem().toString();

        if (code.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "mã số sinh viên không được bỏ trống");
            txtmssv.requestFocus();
            return;
        }
        if (name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "họ tên không được bỏ trống");
            txtname.requestFocus();
            return;
        }
        if (lop.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lớp không được bỏ trống");
            CbLop.requestFocus();
            return;
        }
        if (cmndString.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "chứng minh nhân dân không được bỏ trống");
            txtcmnd.requestFocus();
            return;
        }
        Classroom itemLopClassroom = GetcodeClass(lop);
        Students oStudent = new Students(itemLopClassroom, code, name, sex, cmndString, code);
        if (insertStudent(oStudent)) {
            JOptionPane.showMessageDialog(null, "Thêm thành công!!!");
            ShowStudentTable(TableStudent, lopAc);
            return;
        }
        JOptionPane.showMessageDialog(null, "Thêm Thất Bại!!!");
    }//GEN-LAST:event_themActionPerformed

    private void TableStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableStudentMouseClicked
        JTable target = (JTable) evt.getSource();
        txtmssv.disable();
        txtmssv.setText(TableStudent.getValueAt(target.getSelectedRow(), 0).toString());
        txtname.setText(TableStudent.getValueAt(target.getSelectedRow(), 1).toString());
        txtcmnd.setText(TableStudent.getValueAt(target.getSelectedRow(), 4).toString());
        rnam.setSelected(true);
        if ((TableStudent.getValueAt(target.getSelectedRow(), 2).toString()).equals("nữ")) {
            rnu.setSelected(true);
        }
        CbLop.setSelectedItem(TableStudent.getValueAt(target.getSelectedRow(), 3).toString());

    }//GEN-LAST:event_TableStudentMouseClicked

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        lammoi();

    }//GEN-LAST:event_button3ActionPerformed
    private void lammoi() {
        txtcmnd.setText("");
        txtmssv.setText("");
        txtmssv.enable();
        txtname.setText("");
        rnam.setSelected(true);
    }
    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        String lopAc = CbListClass.getSelectedItem().toString();
        String name = txtname.getText();
        String code = txtmssv.getText();
        String cmndString = txtcmnd.getText();
        Byte sex = 0;
        if (rnu.isSelected()) {
            sex = 1;
        }
        String lop = CbLop.getSelectedItem().toString();

        if (code.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "mã số sinh viên không được bỏ trống");
            txtmssv.requestFocus();
            return;
        }
        if (name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "họ tên không được bỏ trống");
            txtname.requestFocus();
            return;
        }
        if (lop.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lớp không được bỏ trống");
            CbLop.requestFocus();
            return;
        }
        if (cmndString.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "chứng minh nhân dân không được bỏ trống");
            txtcmnd.requestFocus();
            return;
        }
        Classroom itemLopClassroom = GetcodeClass(lop);
        Students item = GetCodeStudent(code);
        System.out.println(item.getId());
        Students oStudent = new Students(item.getId(), itemLopClassroom, code, name, sex, cmndString, code);
        if (editStudent(oStudent)) {
            JOptionPane.showMessageDialog(null, "sửa thành công!!!");
            ShowStudentTable(TableStudent, lopAc);
            lammoi();
            return;
        }
        JOptionPane.showMessageDialog(null, "sửa Thất Bại!!!");
    }//GEN-LAST:event_suaActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        String lopAc = CbListClass.getSelectedItem().toString();
        String code = txtmssv.getText();
        Students item = GetCodeStudent(code);
        System.out.println(item.getId());
        if (deleteStudent(item.getId())) {
            JOptionPane.showMessageDialog(null, "xóa thành công!!!");
            ShowStudentTable(TableStudent, lopAc);
            lammoi();
            return;
        }
        JOptionPane.showMessageDialog(null, "xóa Thất Bại!!!");
    }//GEN-LAST:event_btndeleteActionPerformed

    private void CbListClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbListClassActionPerformed
        String lopAc = CbListClass.getSelectedItem().toString();
        ShowStudentTable(TableStudent, lopAc);
    }//GEN-LAST:event_CbListClassActionPerformed

    private void CbLopLichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbLopLichActionPerformed
        String lopAc = CbLopLich.getSelectedItem().toString();
        ShowScheduleTable(TableLich, lopAc);
    }//GEN-LAST:event_CbLopLichActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Main mainFrame = new Main();
            //mainFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            mainFrame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbListClass;
    private javax.swing.JComboBox<String> CbLop;
    private javax.swing.JComboBox<String> CbLopLich;
    private javax.swing.JTable TableLich;
    private javax.swing.JTable TableStudent;
    private java.awt.Button btndelete;
    private java.awt.Button button3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JPanel panelListScore;
    private javax.swing.JPanel panelStudent;
    private javax.swing.JPanel panelThoikb;
    private javax.swing.JRadioButton rnam;
    private javax.swing.JRadioButton rnu;
    private java.awt.Button sua;
    private java.awt.Button them;
    private javax.swing.JButton toolbarListStudent;
    private javax.swing.JButton toolbarPhucKhao;
    private javax.swing.JButton toolbarSchedule;
    private javax.swing.JButton toolbarScores;
    private javax.swing.JTextField txtcmnd;
    private javax.swing.JTextField txtmssv;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables

}
