/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import static dao.ClassRoomDAO.GetcodeClass;
import static dao.ClassRoomDAO.showClassComboBoxModel;
import static dao.HandleFile.ReadWriteFileImSchedule;
import static dao.HandleFile.ReadWriteFileImScores;
import static dao.HandleFile.ReadWriteFileImStudent;
import static dao.RefencesDAO.Referencescheck;
import static dao.RefencesDAO.ShowRefencesTable;
import static dao.RefencesDAO.editReferences;
import static dao.ScheduleDAO.ShowScheduleTable;
import static dao.ScheduleDAO.showScheduleComboBoxModel;
import static dao.ScheduleReferencesDAO.ShowScheduleReferencesTable;
import static dao.ScheduleReferencesDAO.insertScheduleReferences;
import static dao.StudentDAO.GetCodeStudent;
import static dao.StudentDAO.ShowStudentTable;
import static dao.StudentDAO.deleteStudent;
import static dao.StudentDAO.editStudent;
import static dao.StudentDAO.insertStudent;
import static dao.TranscriptDAO.ShowScoresTable;
import static dao.TranscriptDAO.editScore;
import static dao.TranscriptDAO.listScores;
import static dao.UserDAO.compareUser;
import static dao.UserDAO.editUser;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import pojo.Classroom;
import pojo.References;
import pojo.ScheduleReferences;
import pojo.Students;
import pojo.Transcripts;
import pojo.Users;

/**
 *
 * @author nguye
 */
public class Main extends javax.swing.JFrame {

    private String username;
    private JFileChooser fileChooser;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        // check nam
        rnam.setSelected(true);
        //remove all
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        //add panel
        jPanelMain.add(panelStudent);
        jPanelMain.repaint();
        jPanelMain.revalidate();
        resetData();
        String lopAc = CbListClass.getSelectedItem().toString();
        ShowStudentTable(TableStudent, lopAc);

    }

    public Main(String username) {
        this.username = username;
        initComponents();

        // check nam
        rnam.setSelected(true);
        //remove all
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        //add panel
        jPanelMain.add(panelStudent);
        jPanelMain.repaint();
        jPanelMain.revalidate();
        resetData();
        String lopAc = CbListClass.getSelectedItem().toString();
        ShowStudentTable(TableStudent, lopAc);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelMain = new javax.swing.JPanel();
        panelListScore = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtDmamonhoc = new javax.swing.JTextField();
        txtDmsv = new javax.swing.JTextField();
        txtdcuoiky = new javax.swing.JTextField();
        txtDtong = new javax.swing.JTextField();
        txtDgiuaky = new javax.swing.JTextField();
        txtdiemkhac = new javax.swing.JTextField();
        txttensv = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        BtnDcapnhat = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTableScores = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        jPanel3 = new javax.swing.JPanel();
        JcomboxMaMonHoc = new javax.swing.JComboBox<>();
        jThongke = new javax.swing.JLabel();
        panelThoikb = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CbLopLich = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableLich = new javax.swing.JTable();
        panelStudent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtmssv = new javax.swing.JTextField();
        txtcmnd = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        rnam = new javax.swing.JRadioButton();
        rnu = new javax.swing.JRadioButton();
        CbLop = new javax.swing.JComboBox<>();
        them = new java.awt.Button();
        sua = new java.awt.Button();
        button3 = new java.awt.Button();
        btndelete = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableStudent = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CbListClass = new javax.swing.JComboBox<>();
        panelTaolichphuckhao = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btntaopk = new javax.swing.JButton();
        dateEnd = new javax.swing.JTextField();
        dateStart = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablichpk = new javax.swing.JTable();
        panelMakhau = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtNhapmkM = new javax.swing.JPasswordField();
        txtdmkCu = new javax.swing.JPasswordField();
        txtDmkM = new javax.swing.JPasswordField();
        btnDoimk = new javax.swing.JButton();
        panelPhucKhao = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnCapnhatPhucKhao = new javax.swing.JButton();
        pkmsv = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        pkmamonhoc = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        comboxpk = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableListPk = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        jToolBar1 = new javax.swing.JToolBar();
        toolbarListStudent = new javax.swing.JButton();
        toolbarSchedule = new javax.swing.JButton();
        toolbarScores = new javax.swing.JButton();
        toolbarPhucKhao = new javax.swing.JButton();
        tbTaophuckhao = new javax.swing.JButton();
        btndoimatkhau = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        j4 = new javax.swing.JMenu();
        importStudent = new javax.swing.JMenu();
        importschedule = new javax.swing.JMenu();
        importScores = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMain.setBackground(new java.awt.Color(102, 255, 102));
        jPanelMain.setLayout(new java.awt.CardLayout());

        panelListScore.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Quản Lý Điểm");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm sửa điểm"));

        jLabel12.setText("Mã Môn Học:");

        jLabel13.setText("Điểm Giữa Kỳ");

        jLabel15.setText("Mã Sinh Viên:");

        jLabel16.setText("Điểm Cuối Kỳ");

        jLabel18.setText("Tên Sinh Viên:");

        jLabel19.setText("Điểm Khác");

        jLabel20.setText("Điểm Tổng:");

        txtDmamonhoc.setEnabled(false);

        txtDmsv.setEnabled(false);

        txttensv.setEnabled(false);

        BtnDcapnhat.setText("Cập nhật điểm");
        BtnDcapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDcapnhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(BtnDcapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BtnDcapnhat)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDgiuaky, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(txtDmamonhoc)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(jLabel17)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(txtDtong, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtdcuoiky))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDmsv, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtdiemkhac, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(txttensv, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(txtDmamonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDmsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttensv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19)
                    .addComponent(txtdiemkhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDgiuaky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdcuoiky, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtDtong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JTableScores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Số Sinh Viên", "Họ Và Tên", "Điểm Giữa kỳ", "Điểm Cuối kỳ", "Điểm Khác", "Điểm Tổng", "Môn Học", "Mã Môn học", "Kết Quả"
            }
        ));
        JTableScores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableScoresMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JTableScores);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thống kê điểm sinh viên"));

        JcomboxMaMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        JcomboxMaMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboxMaMonHocActionPerformed(evt);
            }
        });

        jThongke.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jThongke.setText("Thống kê?");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(JcomboxMaMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jThongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JcomboxMaMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jThongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelListScoreLayout = new javax.swing.GroupLayout(panelListScore);
        panelListScore.setLayout(panelListScoreLayout);
        panelListScoreLayout.setHorizontalGroup(
            panelListScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        panelListScoreLayout.setVerticalGroup(
            panelListScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListScoreLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelMain.add(panelListScore, "card4");

        panelThoikb.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Quản lý thời khóa biểu");

        jLabel10.setText("Chọn Lớp:");

        CbLopLich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        CbLopLich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbLopLichActionPerformed(evt);
            }
        });

        TableLich.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Môn", "Tên Môn", "Phòng Học", "Lớp"
            }
        ));
        jScrollPane2.setViewportView(TableLich);

        javax.swing.GroupLayout panelThoikbLayout = new javax.swing.GroupLayout(panelThoikb);
        panelThoikb.setLayout(panelThoikbLayout);
        panelThoikbLayout.setHorizontalGroup(
            panelThoikbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
            .addGroup(panelThoikbLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(CbLopLich, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelThoikbLayout.setVerticalGroup(
            panelThoikbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThoikbLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(panelThoikbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CbLopLich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelMain.add(panelThoikb, "card3");

        panelStudent.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Sinh Viên");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Thêm Xóa Sửa Sinh Viên")));
        jPanel2.setName("Thêm Sửa Sinh Vien"); // NOI18N

        jLabel2.setText("Mã Số Sinh Viên:");

        jLabel3.setText("Họ Và Tên:");

        jLabel7.setText("Giới Tính:");

        jLabel8.setText("Chứng Minh Nhân Dân:");

        jLabel9.setText("Lớp:");

        buttonGroup1.add(rnam);
        rnam.setText("nam");

        buttonGroup1.add(rnu);
        rnu.setText("nu");

        CbLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbLopActionPerformed(evt);
            }
        });

        them.setActionCommand("btnthem");
        them.setLabel("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        sua.setActionCommand("btnSua");
        sua.setLabel("Sửa");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        button3.setActionCommand("btxReset");
        button3.setLabel("Làm Mới");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        btndelete.setActionCommand("btnXoa");
        btndelete.setLabel("Xóa");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmssv)
                            .addComponent(CbLop, 0, 136, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rnam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rnu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcmnd)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(sua, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(txtmssv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rnam)
                    .addComponent(rnu))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CbLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Số Sinh Viên", "Tên Sinh Viên", "Giới Tính", "Lớp", "Chứng minh nhân dân"
            }
        ));
        TableStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableStudent);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Danh Sách Sinh Viên");

        jLabel5.setText("Chọn Lớp: ");

        CbListClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        CbListClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbListClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelStudentLayout = new javax.swing.GroupLayout(panelStudent);
        panelStudent.setLayout(panelStudentLayout);
        panelStudentLayout.setHorizontalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStudentLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CbListClass, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelStudentLayout.setVerticalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CbListClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelMain.add(panelStudent, "card2");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Lịch Phúc Khảo");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tạo Lịch Phúc Khảo"));

        jLabel21.setText("Ngày Bắt Đầu:");

        jLabel22.setText("Ngày Kết Thúc");

        btntaopk.setText("Tạo");
        btntaopk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaopkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(btntaopk)))
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btntaopk)
                .addGap(26, 26, 26))
        );

        tablichpk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Ngày Bắt Đầu", "Ngày Kết Thúc"
            }
        ));
        jScrollPane4.setViewportView(tablichpk);

        javax.swing.GroupLayout panelTaolichphuckhaoLayout = new javax.swing.GroupLayout(panelTaolichphuckhao);
        panelTaolichphuckhao.setLayout(panelTaolichphuckhaoLayout);
        panelTaolichphuckhaoLayout.setHorizontalGroup(
            panelTaolichphuckhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
        );
        panelTaolichphuckhaoLayout.setVerticalGroup(
            panelTaolichphuckhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTaolichphuckhaoLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelMain.add(panelTaolichphuckhao, "card5");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Đổi Mật Khẩu");

        jPanel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Mật Khẩu Cũ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Mật Khẩu Mới");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Nhập Lại Mật Khẩu Mới:");

        btnDoimk.setText("Submit");
        btnDoimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoimkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(txtNhapmkM, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel24))
                                .addGap(79, 79, 79)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtdmkCu)
                                    .addComponent(txtDmkM, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(btnDoimk, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdmkCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNhapmkM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtDmkM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel26)))
                .addGap(102, 102, 102)
                .addComponent(btnDoimk)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMakhauLayout = new javax.swing.GroupLayout(panelMakhau);
        panelMakhau.setLayout(panelMakhauLayout);
        panelMakhauLayout.setHorizontalGroup(
            panelMakhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMakhauLayout.setVerticalGroup(
            panelMakhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMakhauLayout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(37, 37, 37)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 353, Short.MAX_VALUE))
        );

        jPanelMain.add(panelMakhau, "card6");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Danh Sách Phúc Khảo");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Cập Nhật Phúc khảo"));

        btnCapnhatPhucKhao.setText("Cập nhật Phúc Khảo");
        btnCapnhatPhucKhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatPhucKhaoActionPerformed(evt);
            }
        });

        jLabel28.setText("Mã Sinh viên:");

        jLabel29.setText("Mã Môn Học:");

        comboxpk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chon", "Cập Nhật", "Không Cập Nhật" }));

        jLabel30.setText("Trạng Thái");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(btnCapnhatPhucKhao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(pkmsv, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel29)
                .addGap(26, 26, 26)
                .addComponent(pkmamonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(comboxpk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(pkmsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pkmamonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(comboxpk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnCapnhatPhucKhao))
        );

        tableListPk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Số Sinh viên", "Họ Và Tên", "Điểm Giữa Kỳ", "Điểm Cuối Kỳ", "Điểm Khác", "Điểm Tổng ", "Môn Học", "Mã MH", "Lý Do", "Trang thái"
            }
        ));
        tableListPk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListPkMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tableListPk);

        javax.swing.GroupLayout panelPhucKhaoLayout = new javax.swing.GroupLayout(panelPhucKhao);
        panelPhucKhao.setLayout(panelPhucKhaoLayout);
        panelPhucKhaoLayout.setHorizontalGroup(
            panelPhucKhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane5)
        );
        panelPhucKhaoLayout.setVerticalGroup(
            panelPhucKhaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPhucKhaoLayout.createSequentialGroup()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 178, Short.MAX_VALUE))
        );

        jPanelMain.add(panelPhucKhao, "card7");

        jToolBar1.setRollover(true);

        toolbarListStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toolbarListStudent.setText("Danh Sách Sinh Viên");
        toolbarListStudent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toolbarListStudent.setFocusable(false);
        toolbarListStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolbarListStudent.setMargin(new java.awt.Insets(2, 14, 2, 15));
        toolbarListStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarListStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarListStudentActionPerformed(evt);
            }
        });
        jToolBar1.add(toolbarListStudent);

        toolbarSchedule.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toolbarSchedule.setText("Thời Khóa Biểu");
        toolbarSchedule.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toolbarSchedule.setFocusable(false);
        toolbarSchedule.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolbarSchedule.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarScheduleActionPerformed(evt);
            }
        });
        jToolBar1.add(toolbarSchedule);

        toolbarScores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toolbarScores.setText("Danh sách điểm");
        toolbarScores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toolbarScores.setFocusable(false);
        toolbarScores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolbarScores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarScoresActionPerformed(evt);
            }
        });
        jToolBar1.add(toolbarScores);

        toolbarPhucKhao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toolbarPhucKhao.setText("Danh sách phúc khảo");
        toolbarPhucKhao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toolbarPhucKhao.setFocusable(false);
        toolbarPhucKhao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolbarPhucKhao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarPhucKhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbarPhucKhaoActionPerformed(evt);
            }
        });
        jToolBar1.add(toolbarPhucKhao);

        tbTaophuckhao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbTaophuckhao.setText("Tạo phúc khảo");
        tbTaophuckhao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbTaophuckhao.setFocusable(false);
        tbTaophuckhao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbTaophuckhao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbTaophuckhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTaophuckhaoActionPerformed(evt);
            }
        });
        jToolBar1.add(tbTaophuckhao);

        btndoimatkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btndoimatkhau.setText("Đổi mật khẩu");
        btndoimatkhau.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndoimatkhau.setFocusable(false);
        btndoimatkhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndoimatkhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btndoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoimatkhauActionPerformed(evt);
            }
        });
        jToolBar1.add(btndoimatkhau);

        j4.setText("File");
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });

        importStudent.setText("ImportStudents");
        importStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importStudentMouseClicked(evt);
            }
        });
        importStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importStudentActionPerformed(evt);
            }
        });
        j4.add(importStudent);

        importschedule.setText("ImportSchedule");
        importschedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importscheduleMouseClicked(evt);
            }
        });
        j4.add(importschedule);

        importScores.setText("ImportScores");
        importScores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importScoresMouseClicked(evt);
            }
        });
        j4.add(importScores);

        jMenuBar1.add(j4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toolbarPhucKhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarPhucKhaoActionPerformed
        ShowRefencesTable(tableListPk, "");
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        //add panel
        jPanelMain.add(panelPhucKhao);
        jPanelMain.repaint();
        jPanelMain.revalidate();
    }//GEN-LAST:event_toolbarPhucKhaoActionPerformed

    private void toolbarListStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarListStudentActionPerformed
        String lopAc = CbListClass.getSelectedItem().toString();
        ShowStudentTable(TableStudent, lopAc);
//remove all
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        //add panel
        jPanelMain.add(panelStudent);
        jPanelMain.repaint();
        jPanelMain.revalidate();

        // add Table;

    }//GEN-LAST:event_toolbarListStudentActionPerformed

    private void toolbarScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarScoresActionPerformed
        String mh = JcomboxMaMonHoc.getSelectedItem().toString();
        ShowScoresTable(JTableScores, mh, jThongke);
//remove all
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        //add panel
        jPanelMain.add(panelListScore);
        jPanelMain.repaint();
        jPanelMain.revalidate();
    }//GEN-LAST:event_toolbarScoresActionPerformed

    private void toolbarScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbarScheduleActionPerformed
        String lopAc = CbLopLich.getSelectedItem().toString();
        ShowScheduleTable(TableLich, lopAc);
//remove all
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        //add panel
        jPanelMain.add(panelThoikb);
        jPanelMain.repaint();
        jPanelMain.revalidate();
    }//GEN-LAST:event_toolbarScheduleActionPerformed

    private void CbLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbLopActionPerformed

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        String lopAc = CbListClass.getSelectedItem().toString();
        String name = txtname.getText();
        String code = txtmssv.getText();
        String cmndString = txtcmnd.getText();
        Byte sex = 0;
        if (rnu.isSelected()) {
            sex = 1;
        }
        String lop = CbLop.getSelectedItem().toString();

        if (code.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "mã số sinh viên không được bỏ trống");
            txtmssv.requestFocus();
            return;
        }
        if (name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "họ tên không được bỏ trống");
            txtname.requestFocus();
            return;
        }
        if (lop.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lớp không được bỏ trống");
            CbLop.requestFocus();
            return;
        }
        if (cmndString.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "chứng minh nhân dân không được bỏ trống");
            txtcmnd.requestFocus();
            return;
        }
        Classroom itemLopClassroom = GetcodeClass(lop);
        Students oStudent = new Students(itemLopClassroom, code, name, sex, cmndString, code);
        if (insertStudent(oStudent)) {
            JOptionPane.showMessageDialog(null, "Thêm thành công!!!");
            ShowStudentTable(TableStudent, lopAc);
            return;
        }
        JOptionPane.showMessageDialog(null, "Thêm Thất Bại!!!");
    }//GEN-LAST:event_themActionPerformed

    private void TableStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableStudentMouseClicked
        JTable target = (JTable) evt.getSource();
        txtmssv.disable();
        txtmssv.setText(TableStudent.getValueAt(target.getSelectedRow(), 0).toString());
        txtname.setText(TableStudent.getValueAt(target.getSelectedRow(), 1).toString());
        txtcmnd.setText(TableStudent.getValueAt(target.getSelectedRow(), 4).toString());
        rnam.setSelected(true);
        if ((TableStudent.getValueAt(target.getSelectedRow(), 2).toString()).equals("nữ")) {
            rnu.setSelected(true);
        }
        CbLop.setSelectedItem(TableStudent.getValueAt(target.getSelectedRow(), 3).toString());

    }//GEN-LAST:event_TableStudentMouseClicked

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        lammoi();

    }//GEN-LAST:event_button3ActionPerformed
    private void lammoi() {
        txtcmnd.setText("");
        txtmssv.setText("");
        txtmssv.enable();
        txtname.setText("");
        rnam.setSelected(true);
    }
    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        String lopAc = CbListClass.getSelectedItem().toString();
        String name = txtname.getText();
        String code = txtmssv.getText();
        String cmndString = txtcmnd.getText();
        Byte sex = 0;
        if (rnu.isSelected()) {
            sex = 1;
        }
        String lop = CbLop.getSelectedItem().toString();

        if (code.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "mã số sinh viên không được bỏ trống");
            txtmssv.requestFocus();
            return;
        }
        if (name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "họ tên không được bỏ trống");
            txtname.requestFocus();
            return;
        }
        if (lop.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lớp không được bỏ trống");
            CbLop.requestFocus();
            return;
        }
        if (cmndString.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "chứng minh nhân dân không được bỏ trống");
            txtcmnd.requestFocus();
            return;
        }
        Classroom itemLopClassroom = GetcodeClass(lop);
        Students item = GetCodeStudent(code);
        System.out.println(item.getId());
        Students oStudent = new Students(item.getId(), itemLopClassroom, code, name, sex, cmndString, code);
        if (editStudent(oStudent)) {
            JOptionPane.showMessageDialog(null, "sửa thành công!!!");
            ShowStudentTable(TableStudent, lopAc);
            lammoi();
            return;
        }
        JOptionPane.showMessageDialog(null, "sửa Thất Bại!!!");
    }//GEN-LAST:event_suaActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        String lopAc = CbListClass.getSelectedItem().toString();
        String code = txtmssv.getText();
        Students item = GetCodeStudent(code);
        System.out.println(item.getId());
        if (deleteStudent(item.getId())) {
            JOptionPane.showMessageDialog(null, "xóa thành công!!!");
            ShowStudentTable(TableStudent, lopAc);
            lammoi();
            return;
        }
        JOptionPane.showMessageDialog(null, "xóa Thất Bại!!!");
    }//GEN-LAST:event_btndeleteActionPerformed

    private void CbListClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbListClassActionPerformed
        String lopAc = "All";
        if (CbListClass.getSelectedItem() != null) {
            lopAc = CbListClass.getSelectedItem().toString();
        }

        ShowStudentTable(TableStudent, lopAc);
    }//GEN-LAST:event_CbListClassActionPerformed

    private void CbLopLichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbLopLichActionPerformed
        String lopAc = "All";
        if (CbLopLich.getSelectedItem() != null) {
            lopAc = CbLopLich.getSelectedItem().toString();
        }
        ShowScheduleTable(TableLich, lopAc);
    }//GEN-LAST:event_CbLopLichActionPerformed

    private void BtnDcapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDcapnhatActionPerformed
        String mamh = txtDmamonhoc.getText().trim();
        String msv = txtDmsv.getText().trim();
        float diemgk = Float.parseFloat(txtDgiuaky.getText().trim());
        float dcuoiky = Float.parseFloat(txtdcuoiky.getText().trim());
        float dkhac = Float.parseFloat(txtdiemkhac.getText().trim());
        float dtong = Float.parseFloat(txtDtong.getText().trim());
        Transcripts Data = new Transcripts(dtong, dcuoiky, dkhac, dtong);
        if (editScore(Data, msv, mamh)) {
            JOptionPane.showMessageDialog(null, "sửa thành công!!!");
            String mh = JcomboxMaMonHoc.getSelectedItem().toString();
            ShowScoresTable(JTableScores, mh, jThongke);
            clearFrom();
            return;
        }
        JOptionPane.showMessageDialog(null, "sửa Thất Bại!!!");

    }//GEN-LAST:event_BtnDcapnhatActionPerformed

    private void JcomboxMaMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboxMaMonHocActionPerformed
        String mh = "All";
        if (JcomboxMaMonHoc.getSelectedItem() != null) {
            mh = JcomboxMaMonHoc.getSelectedItem().toString();
        }
        ShowScoresTable(JTableScores, mh, jThongke);  // TODO add your handling code here:
    }//GEN-LAST:event_JcomboxMaMonHocActionPerformed

    private void JTableScoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableScoresMouseClicked
        JTable target = (JTable) evt.getSource();
        txtDmsv.setText(JTableScores.getValueAt(target.getSelectedRow(), 0).toString());
        txtDmamonhoc.setText(JTableScores.getValueAt(target.getSelectedRow(), 7).toString());
        txttensv.setText(JTableScores.getValueAt(target.getSelectedRow(), 1).toString());
        txtDgiuaky.setText(JTableScores.getValueAt(target.getSelectedRow(), 2).toString());
        txtdcuoiky.setText(JTableScores.getValueAt(target.getSelectedRow(), 3).toString());
        txtdiemkhac.setText(JTableScores.getValueAt(target.getSelectedRow(), 4).toString());
        txtDtong.setText(JTableScores.getValueAt(target.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_JTableScoresMouseClicked

    private void tbTaophuckhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTaophuckhaoActionPerformed
        ShowScheduleReferencesTable(tablichpk);
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        //add panel
        jPanelMain.add(panelTaolichphuckhao);
        jPanelMain.repaint();
        jPanelMain.revalidate();
    }//GEN-LAST:event_tbTaophuckhaoActionPerformed

    private void btndoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoimatkhauActionPerformed
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        //add panel
        jPanelMain.add(panelMakhau);
        jPanelMain.repaint();
        jPanelMain.revalidate();
    }//GEN-LAST:event_btndoimatkhauActionPerformed

    private void btnDoimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoimkActionPerformed
        String mkcu = txtdmkCu.getText();
        String mkmoi = txtDmkM.getText();
        String mkmoinlString = txtNhapmkM.getText();
        if (mkmoi.trim().equals(mkmoinlString.trim())) {
            Users giaovu = compareUser(this.username, mkcu);
            if (giaovu != null) {
                giaovu.setPassword(mkmoi);
                if (editUser(giaovu)) {
                    JOptionPane.showMessageDialog(null, "Thay đổi thành công!");
                    this.setVisible(false);
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            Login_Form form = new Login_Form();
                            //form.setExtendedState(JFrame.MAXIMIZED_BOTH);
                            form.setVisible(true);
                        }
                    });
                    return;
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Kiểm Tra Lại Mật Khẩu !!");
        return;
    }//GEN-LAST:event_btnDoimkActionPerformed

    private void tableListPkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListPkMouseClicked
        JTable target = (JTable) evt.getSource();
        pkmsv.setText(tableListPk.getValueAt(target.getSelectedRow(), 0).toString());
        pkmamonhoc.setText(tableListPk.getValueAt(target.getSelectedRow(), 7).toString());
    }//GEN-LAST:event_tableListPkMouseClicked

    private void btnCapnhatPhucKhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatPhucKhaoActionPerformed
        String codemsv = pkmsv.getText();
        String codemmh = pkmamonhoc.getText();
        int status = comboxpk.getSelectedIndex();
        Byte trangthaiByte = 1;
        if (status == 2) {
            trangthaiByte = 2;
        }
        References item = Referencescheck(codemsv, codemmh);
        item.setStatus(trangthaiByte);
        if (editReferences(item)) {
            JOptionPane.showMessageDialog(null, "sửa thành công!!!");
            ShowRefencesTable(tableListPk, "");
            pkmamonhoc.setText("");
            pkmsv.setText("");
            return;
        }
        JOptionPane.showMessageDialog(null, "sửa thất bại!!!");
        return;
    }//GEN-LAST:event_btnCapnhatPhucKhaoActionPerformed

    private void btntaopkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaopkActionPerformed
        Date start, end;
        try {
            start = new SimpleDateFormat("dd-MM-yyyy").parse(dateStart.getText());
            end = new SimpleDateFormat("dd-MM-yyyy").parse(dateEnd.getText());
            System.err.println(end);
            ScheduleReferences item = new ScheduleReferences(start, end);
            if (insertScheduleReferences(item)) {
                JOptionPane.showMessageDialog(null, "Thêm thành công!!!");
                ShowScheduleReferencesTable(tablichpk);
                pkmamonhoc.setText("");
                pkmsv.setText("");
                return;
            }
        } catch (ParseException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Thêm thất bại!!!");
        return;
    }//GEN-LAST:event_btntaopkActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed

    }//GEN-LAST:event_j4ActionPerformed

    private void importStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importStudentActionPerformed

    }//GEN-LAST:event_importStudentActionPerformed

    private void importStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importStudentMouseClicked
        fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(Main.this) == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getPath();
            if (ReadWriteFileImStudent(filePath)) {
                resetData();
                String lopAc = CbListClass.getSelectedItem().toString();
                ShowStudentTable(TableStudent, lopAc);

                JOptionPane.showMessageDialog(null, "Nhập sinh viên thành công!!!");
                return;
            }

        }
        JOptionPane.showMessageDialog(null, "Nhập sinh viên thất bại!!!");
        return;
    }//GEN-LAST:event_importStudentMouseClicked

    private void importscheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importscheduleMouseClicked
        fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(Main.this) == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getPath();
            if (ReadWriteFileImSchedule(filePath)) {
                resetData();
                String lopAc = CbLopLich.getSelectedItem().toString();
                ShowScheduleTable(TableLich, lopAc);
                String mh = JcomboxMaMonHoc.getSelectedItem().toString();
                ShowScoresTable(JTableScores, mh, jThongke);

                JOptionPane.showMessageDialog(null, "Nhập thời khóa biểu thành công!!!");
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Nhập thời khóa biểu thất bại!!!");
        return;
    }//GEN-LAST:event_importscheduleMouseClicked

    private void importScoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importScoresMouseClicked
        fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(Main.this) == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getPath();
            if (ReadWriteFileImScores(filePath)) {
                resetData();
                String mh = JcomboxMaMonHoc.getSelectedItem().toString();
                ShowScoresTable(JTableScores, mh, jThongke);

                JOptionPane.showMessageDialog(null, "import thành công!!!");
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "import biểu thất bại!!!");
        return;
    }//GEN-LAST:event_importScoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Main mainFrame = new Main();
            //mainFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            mainFrame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDcapnhat;
    private javax.swing.JComboBox<String> CbListClass;
    private javax.swing.JComboBox<String> CbLop;
    private javax.swing.JComboBox<String> CbLopLich;
    private javax.swing.JTable JTableScores;
    private javax.swing.JComboBox<String> JcomboxMaMonHoc;
    private javax.swing.JTable TableLich;
    private javax.swing.JTable TableStudent;
    private javax.swing.JButton btnCapnhatPhucKhao;
    private javax.swing.JButton btnDoimk;
    private java.awt.Button btndelete;
    private javax.swing.JButton btndoimatkhau;
    private javax.swing.JButton btntaopk;
    private java.awt.Button button3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboxpk;
    private javax.swing.JTextField dateEnd;
    private javax.swing.JTextField dateStart;
    private javax.swing.JMenu importScores;
    private javax.swing.JMenu importStudent;
    private javax.swing.JMenu importschedule;
    private javax.swing.JMenu j4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel jThongke;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panelListScore;
    private javax.swing.JPanel panelMakhau;
    private javax.swing.JPanel panelPhucKhao;
    private javax.swing.JPanel panelStudent;
    private javax.swing.JPanel panelTaolichphuckhao;
    private javax.swing.JPanel panelThoikb;
    private javax.swing.JTextField pkmamonhoc;
    private javax.swing.JTextField pkmsv;
    private javax.swing.JRadioButton rnam;
    private javax.swing.JRadioButton rnu;
    private java.awt.Button sua;
    private javax.swing.JTable tableListPk;
    private javax.swing.JTable tablichpk;
    private javax.swing.JButton tbTaophuckhao;
    private java.awt.Button them;
    private javax.swing.JButton toolbarListStudent;
    private javax.swing.JButton toolbarPhucKhao;
    private javax.swing.JButton toolbarSchedule;
    private javax.swing.JButton toolbarScores;
    private javax.swing.JTextField txtDgiuaky;
    private javax.swing.JTextField txtDmamonhoc;
    private javax.swing.JPasswordField txtDmkM;
    private javax.swing.JTextField txtDmsv;
    private javax.swing.JTextField txtDtong;
    private javax.swing.JPasswordField txtNhapmkM;
    private javax.swing.JTextField txtcmnd;
    private javax.swing.JTextField txtdcuoiky;
    private javax.swing.JTextField txtdiemkhac;
    private javax.swing.JPasswordField txtdmkCu;
    private javax.swing.JTextField txtmssv;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txttensv;
    // End of variables declaration//GEN-END:variables

    private void clearFrom() {
        txtDgiuaky.setText("");
        txtDmamonhoc.setText("");
        txtDmsv.setText("");
        txtDtong.setText("");
        txtDmamonhoc.setText("");
        txttensv.setText("");
        txtdiemkhac.setText("");
        txtdcuoiky.setText("");
    }

    private void resetData() {
        showClassComboBoxModel(CbLop, 0);
        showClassComboBoxModel(CbListClass, 1);
        showClassComboBoxModel(CbLopLich, 1);
        showScheduleComboBoxModel(JcomboxMaMonHoc);
    }

}
