package pojo;
// Generated Aug 17, 2019 10:44:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Classroom generated by hbm2java
 */
public class Classroom  implements java.io.Serializable {


     private Integer id;
     private String code;
     private Set scheduleses = new HashSet(0);
     private Set studentses = new HashSet(0);

    public Classroom() {
    }

    public Classroom(String code) {
        this.code = code;
    }
    
    public Classroom(String code, Set scheduleses, Set studentses) {
       this.code = code;
       this.scheduleses = scheduleses;
       this.studentses = studentses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Set getScheduleses() {
        return this.scheduleses;
    }
    
    public void setScheduleses(Set scheduleses) {
        this.scheduleses = scheduleses;
    }
    public Set getStudentses() {
        return this.studentses;
    }
    
    public void setStudentses(Set studentses) {
        this.studentses = studentses;
    }




}


