package pojo;
// Generated Aug 14, 2019 11:04:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lop generated by hbm2java
 */
public class Lop  implements java.io.Serializable {


     private Integer id;
     private String codeClass;
     private Set<ThoiKhoaBieu> thoiKhoaBieus = new HashSet<ThoiKhoaBieu>(0);

    public Lop() {
    }

    public Lop(String codeClass, Set<ThoiKhoaBieu> thoiKhoaBieus) {
       this.codeClass = codeClass;
       this.thoiKhoaBieus = thoiKhoaBieus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodeClass() {
        return this.codeClass;
    }
    
    public void setCodeClass(String codeClass) {
        this.codeClass = codeClass;
    }
    public Set<ThoiKhoaBieu> getThoiKhoaBieus() {
        return this.thoiKhoaBieus;
    }
    
    public void setThoiKhoaBieus(Set<ThoiKhoaBieu> thoiKhoaBieus) {
        this.thoiKhoaBieus = thoiKhoaBieus;
    }




}


