package pojo;
// Generated Aug 23, 2019 11:34:39 PM by Hibernate Tools 4.3.1



/**
 * References generated by hbm2java
 */
public class References  implements java.io.Serializable {


     private Integer id;
     private String codeStudent;
     private String name;
     private String nameSubjects;
     private String codeSubjects;
     private Float midtermScores;
     private Float finalScores;
     private Float totalScores;
     private Float orderScores;
     private String reason;
     private Byte status;

    public References() {
    }

    public References(String codeStudent, String name, String nameSubjects, String codeSubjects, Float midtermScores, Float finalScores, Float totalScores, Float orderScores, String reason, Byte status) {
       this.codeStudent = codeStudent;
       this.name = name;
       this.nameSubjects = nameSubjects;
       this.codeSubjects = codeSubjects;
       this.midtermScores = midtermScores;
       this.finalScores = finalScores;
       this.totalScores = totalScores;
       this.orderScores = orderScores;
       this.reason = reason;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodeStudent() {
        return this.codeStudent;
    }
    
    public void setCodeStudent(String codeStudent) {
        this.codeStudent = codeStudent;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNameSubjects() {
        return this.nameSubjects;
    }
    
    public void setNameSubjects(String nameSubjects) {
        this.nameSubjects = nameSubjects;
    }
    public String getCodeSubjects() {
        return this.codeSubjects;
    }
    
    public void setCodeSubjects(String codeSubjects) {
        this.codeSubjects = codeSubjects;
    }
    public Float getMidtermScores() {
        return this.midtermScores;
    }
    
    public void setMidtermScores(Float midtermScores) {
        this.midtermScores = midtermScores;
    }
    public Float getFinalScores() {
        return this.finalScores;
    }
    
    public void setFinalScores(Float finalScores) {
        this.finalScores = finalScores;
    }
    public Float getTotalScores() {
        return this.totalScores;
    }
    
    public void setTotalScores(Float totalScores) {
        this.totalScores = totalScores;
    }
    public Float getOrderScores() {
        return this.orderScores;
    }
    
    public void setOrderScores(Float orderScores) {
        this.orderScores = orderScores;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }




}


