package pojo;
// Generated Aug 17, 2019 10:44:46 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Schedules generated by hbm2java
 */
public class Schedules implements java.io.Serializable {

    private Integer id;
    private Classroom classroom;
    private String code;
    private String name;
    private String room;
    private Set<Transcripts> transcriptses = new HashSet<Transcripts>();

    public Schedules() {
    }

    public Schedules(Classroom classroom, String code, String name, String room) {
        this.classroom = classroom;
        this.code = code;
        this.name = name;
        this.room = room;
    }

    public Set<Transcripts> getTranscriptses() {
        return transcriptses;
    }

    public void setTranscriptses(Set<Transcripts> transcriptses) {
        this.transcriptses = transcriptses;
    }
    
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Classroom getClassroom() {
        return this.classroom;
    }

    public void setClassroom(Classroom classroom) {
        this.classroom = classroom;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRoom() {
        return this.room;
    }

    public void setRoom(String room) {
        this.room = room;
    }

}
