package pojo;
// Generated Aug 23, 2019 11:34:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ScheduleReferences generated by hbm2java
 */
public class ScheduleReferences  implements java.io.Serializable {


     private int id;
     private Date start;
     private Date end;

    public ScheduleReferences() {
    }

	
    public ScheduleReferences(int id) {
        this.id = id;
    }
    public ScheduleReferences(int id, Date start, Date end) {
       this.id = id;
       this.start = start;
       this.end = end;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }




}


