package pojo;
// Generated Aug 14, 2019 11:04:11 PM by Hibernate Tools 4.3.1



/**
 * ThoiKhoaBieu generated by hbm2java
 */
public class ThoiKhoaBieu  implements java.io.Serializable {


     private Integer id;
     private Lop lop;
     private String code;
     private String name;
     private String room;

    public ThoiKhoaBieu() {
    }

    public ThoiKhoaBieu(Lop lop, String code, String name, String room) {
       this.lop = lop;
       this.code = code;
       this.name = name;
       this.room = room;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Lop getLop() {
        return this.lop;
    }
    
    public void setLop(Lop lop) {
        this.lop = lop;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRoom() {
        return this.room;
    }
    
    public void setRoom(String room) {
        this.room = room;
    }




}


