package pojo;
// Generated Aug 23, 2019 11:34:39 PM by Hibernate Tools 4.3.1



/**
 * TranscriptsId generated by hbm2java
 */
public class TranscriptsId  implements java.io.Serializable {


     private Integer scheduleId;
     private Integer studentId;
     private Float midtermScores;
     private Float finalScores;
     private Float otherScores;
     private Float totalScores;
     private Byte status;

    public TranscriptsId() {
    }

    public TranscriptsId(Integer scheduleId, Integer studentId, Float midtermScores, Float finalScores, Float otherScores, Float totalScores, Byte status) {
       this.scheduleId = scheduleId;
       this.studentId = studentId;
       this.midtermScores = midtermScores;
       this.finalScores = finalScores;
       this.otherScores = otherScores;
       this.totalScores = totalScores;
       this.status = status;
    }
   
    public Integer getScheduleId() {
        return this.scheduleId;
    }
    
    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
    public Float getMidtermScores() {
        return this.midtermScores;
    }
    
    public void setMidtermScores(Float midtermScores) {
        this.midtermScores = midtermScores;
    }
    public Float getFinalScores() {
        return this.finalScores;
    }
    
    public void setFinalScores(Float finalScores) {
        this.finalScores = finalScores;
    }
    public Float getOtherScores() {
        return this.otherScores;
    }
    
    public void setOtherScores(Float otherScores) {
        this.otherScores = otherScores;
    }
    public Float getTotalScores() {
        return this.totalScores;
    }
    
    public void setTotalScores(Float totalScores) {
        this.totalScores = totalScores;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TranscriptsId) ) return false;
		 TranscriptsId castOther = ( TranscriptsId ) other; 
         
		 return ( (this.getScheduleId()==castOther.getScheduleId()) || ( this.getScheduleId()!=null && castOther.getScheduleId()!=null && this.getScheduleId().equals(castOther.getScheduleId()) ) )
 && ( (this.getStudentId()==castOther.getStudentId()) || ( this.getStudentId()!=null && castOther.getStudentId()!=null && this.getStudentId().equals(castOther.getStudentId()) ) )
 && ( (this.getMidtermScores()==castOther.getMidtermScores()) || ( this.getMidtermScores()!=null && castOther.getMidtermScores()!=null && this.getMidtermScores().equals(castOther.getMidtermScores()) ) )
 && ( (this.getFinalScores()==castOther.getFinalScores()) || ( this.getFinalScores()!=null && castOther.getFinalScores()!=null && this.getFinalScores().equals(castOther.getFinalScores()) ) )
 && ( (this.getOtherScores()==castOther.getOtherScores()) || ( this.getOtherScores()!=null && castOther.getOtherScores()!=null && this.getOtherScores().equals(castOther.getOtherScores()) ) )
 && ( (this.getTotalScores()==castOther.getTotalScores()) || ( this.getTotalScores()!=null && castOther.getTotalScores()!=null && this.getTotalScores().equals(castOther.getTotalScores()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getScheduleId() == null ? 0 : this.getScheduleId().hashCode() );
         result = 37 * result + ( getStudentId() == null ? 0 : this.getStudentId().hashCode() );
         result = 37 * result + ( getMidtermScores() == null ? 0 : this.getMidtermScores().hashCode() );
         result = 37 * result + ( getFinalScores() == null ? 0 : this.getFinalScores().hashCode() );
         result = 37 * result + ( getOtherScores() == null ? 0 : this.getOtherScores().hashCode() );
         result = 37 * result + ( getTotalScores() == null ? 0 : this.getTotalScores().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         return result;
   }   


}


