package Models;
// Generated Aug 13, 2019 9:20:47 PM by Hibernate Tools 4.3.1



/**
 * Schedule generated by hbm2java
 */
public class Schedule  implements java.io.Serializable {


     private Integer id;
     private Classes classes;
     private String code;
     private String name;
     private String room;

    public Schedule() {
    }

    public Schedule(Classes classes, String code, String name, String room) {
       this.classes = classes;
       this.code = code;
       this.name = name;
       this.room = room;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Classes getClasses() {
        return this.classes;
    }
    
    public void setClasses(Classes classes) {
        this.classes = classes;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRoom() {
        return this.room;
    }
    
    public void setRoom(String room) {
        this.room = room;
    }




}


