package Models;
// Generated Aug 13, 2019 9:20:47 PM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private Integer id;
     private Classes classes;
     private String name;
     private String studentCode;
     private byte sex;
     private int identityCard;
     private String password;

    public Student() {
    }

    public Student(Classes classes, String name, String studentCode, byte sex, int identityCard, String password) {
       this.classes = classes;
       this.name = name;
       this.studentCode = studentCode;
       this.sex = sex;
       this.identityCard = identityCard;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Classes getClasses() {
        return this.classes;
    }
    
    public void setClasses(Classes classes) {
        this.classes = classes;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStudentCode() {
        return this.studentCode;
    }
    
    public void setStudentCode(String studentCode) {
        this.studentCode = studentCode;
    }
    public byte getSex() {
        return this.sex;
    }
    
    public void setSex(byte sex) {
        this.sex = sex;
    }
    public int getIdentityCard() {
        return this.identityCard;
    }
    
    public void setIdentityCard(int identityCard) {
        this.identityCard = identityCard;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


